"""Immergas boiler fault descriptions (English).

Extracted 1:1 from the decoded Dominus app label table
(LBL-WFC01_IM_MBUS_MPROCOMBOV2.json, `text1-en`/`text2-en`/`action-en`), the same
source the D+/D- and T-/T+ tooling used. Fault code lives in PDU 2100 (0 = no fault);
the reset-available flag in PDU 2101 bit 1."""
from __future__ import annotations

ANOMALIES: dict[int, str] = {
    1: "No ignition block. Failure to detect the flame at the end of the last attempt at ignition → Press the Reset button",
    2: "Safety thermostat block (over-temperature). The safety thermostat has intervened → Press the Reset button",
    3: "Flue safety thermostat block. The flue safety thermostat has intervened → Press the Reset button (Nike versions)/ Correctly configure the P.14 parameter. Press the Reset button if required (Star versions)",
    4: "Contacts resistance block. Detected an abnormality in the driving circuit of the gas valve → The boiler does not start. If the shutdown or fault persists, contact an authorised company (e.g. Authorised Technical After-Sales Service).",
    5: "Flow probe anomaly. The flow sensor provides a resistive value out of range → The boiler does not start. If the shutdown or fault persists, contact an authorised company (e.g. Authorised Technical After-Sales Service).",
    6: "Domestic hot water probe anomaly. The Domestic hot water sensor provides a resistive value out of range → In this case the boiler continues to produce domestic hot water but not with optimal performance. If the shutdown or fault persists, contact an authorised company (e.g. Authorised Technical After-Sales Service).",
    8: "Maximum N° of reset. Indicates the maximum number of reset allowed by integrated P.C.B. → Attention: the anomaly can be reset 5 times consecutively, after which the function in inhibited for at least one hour. One attempt is gained every hour for a maximum of 5 attempts. By switching the appliance on and off again, the 5 attempts are re-acquired.",
    10: "Insufficient system pressure. The pressure switch contact is open → Check on the boiler pressure gauge that the system pressure is between 1÷1.2 bar and restore the correct pressure if necessary.",
    11: "Flue pressure switch anomaly. This occurs in case of a fault in the flue pressure switch or the fan. → If the shutdown or fault persists, contact an authorised company (e.g. Authorised Technical After-Sales Service)",
    12: "Storage tank probe anomaly. The domestic hot water tank sensor provides a resistive value out of range → The boiler does not satisfy the DHW production requests. If the shutdown or fault persists, contact an authorised company (e.g. Authorised Technical After-Sales Service).",
    13: "Air/flue gas flow-meter out of range. The air/flue gas signal is out of range or with fan stopped, the controller reads an excessively high signal → If the block or anomaly persists, contact an authorised company (e.g. Immergas Technical After-Sales Service).",
    15: "Configuration error. The P.C.B. finds a mismatch between the configuration and the input signals → If normal conditions are restored the boiler restarts without having to be reset. Check that the boiler is configured correctly. If the shutdown or fault persists, contact an authorised company (e.g. Authorised Technical After-Sales Service).",
    16: "Fan anomaly. The fan is rotated when it is not powered or is stationary when powered → Press the Reset button. If the shutdown or fault persists, contact an authorised company (e.g. Authorised Technical After-Sales Service).",
    17: "Incorrect fan speed. The number of fan revolutions is out of the correct range → If the block or anomaly persists, contact an authorised company (e.g. Immergas Technical After-Sales Service).",
    20: "Parasite flame block. Flame detection abnormal → Press the Reset button. If the shutdown or fault persists, contact an authorised company (e.g. Authorised Technical After-Sales Service).",
    23: "Return probe anomaly. The return sensor provides a resistive value out of range → The boiler does not start. If the shutdown or fault persists, contact an authorised company (e.g. Authorised Technical After-Sales Service).",
    24: "Push button control panel anomaly. It is detected a continuous pressure on the dashboard buttons → If normal conditions are restored the boiler restarts without having to be reset. If the shutdown or fault persists, contact an authorised company (e.g. Authorised Technical After-Sales Service).",
    25: "Flue probe block / CRC block (TERA). Flue gas temperature out of range / memory corrupted (TERA) → Press the Reset button",
    27: "Insufficient circulation. Overheating of the boiler due to poor circulation in the primary circuit → Press the Reset button",
    28: "Domestic hot water leakage. If during the heating stage, a rise in domestic hot water temperature occurs, an anomaly is signalled and heating temperature is reduced to limit the formation of limescale in the heat exchanger. → If the shutdown or fault persists, contact an authorised company (e.g. Authorised Technical After-Sales Service)",
    29: "Flue probe anomaly. The flue sensor provides a resistive value out of range → The boiler does not start. If the shutdown or fault persists, contact an authorised company (e.g. Authorised Technical After-Sales Service).",
    31: "Loss of communication with the CARV2. There is no communication between the boiler and remote. → Power cycle the boiler. If the Remote Control is still not detected on re-starting the boiler will switch to local operating mode, i.e. using the controls on the control panel. In this case the ''Central Heating'' mode cannot be activated.",
    32: "Zone 2 low temperature probe anomaly. Zone 2 flow probe out of range → If the block or anomaly persists, contact an authorised company (e.g. Immergas Technical After-Sales Service).",
    33: "Zone 3 low temperature probe anomaly. Zone 3 flow probe out of range → If the block or anomaly persists, contact an authorised company (e.g. Immergas Technical After-Sales Service).",
    36: "IMG Bus communication loss. Loss of communication on the IMG Bus protocol. → The boiler does not satisfy the room heating requests.",
    37: "Low power supply voltage. The P.C.B. supply voltage has values below the allowed limits. → If normal conditions are restored the boiler restarts without having to be reset.",
    38: "Loss of flame signal. The P.C.B., after detecting a correct flame current value, signaling a drop in flame current. → If normal conditions are restored the boiler restarts without having to be reset.",
    39: "Solar collector probe anomaly. The external probe has an out of range resistive value → If the block or anomaly persists, contact an authorised company (e.g. Immergas Technical After-Sales Service).",
    40: "Solar storage tank probe anomaly. The solar storage tank has an out of range resistive value → If the block or anomaly persists, contact an authorised company (e.g. Immergas Technical After-Sales Service).",
    41: "High temperature on the solar collector. The solar collector has exceeded the maximum temperature set → If the block or anomaly persists, contact an authorised company (e.g. Immergas Technical After-Sales Service).",
    42: "High temperature on the solar storage tank. The solar storage tank has exceeded the maximum temperature set → If the block or anomaly persists, contact an authorised company (e.g. Immergas Technical After-Sales Service).",
    43: "Block due to loss of flame signal. Loss of flame signal during operation in regimen for more consecutive times. → Press the Reset button, before restarting, the boiler will run a post-ventilation cycle.",
    44: "Block for exceeding the maximum accumulated time, close gas valve opening. The accumulation of the total time of the gas valve opened without flame detection is greater than the maximum allowed. → Press the Reset button.",
    45: "dT high. The temperature difference measured between flow and return is ≥ 40 ° C. → The power of the burner is limited to prevent damage to the condensation module and once the right dT is restored, the boiler resumes regular operation. Make sure there is water circulating in the boiler, that the pump is configured according to system requirements and that the return probe works properly.",
    46: "Low temperature thermostat intervention / Incorrect wiring/board configuration. The safety thermostat on the boiler flow connection to DIM v2 (operating only at Low Temperature) has reached high temperatures. / Wiring error or use of incorrect spare board → In this case, after cooling down, it is possible to reset the thermostat (see relative instruction sheet). / If the blockage or anomaly persists it is necessary to call an authorised company (e.g. Immergas Technical Assistance Service).",
    47: "Burner power limitation. If the flue gas temperature reaches a high value the card reduces the power supplied by the burner, in order to limit damage to the smoke circuit. → If the shutdown or fault persists, contact an authorised company (e.g. Authorised Technical After-Sales Service).",
    48: "System side flow probe anomaly. The system side flow probe has an out of range resistive value → If the block or anomaly persists, contact an authorised company (e.g. Immergas Technical After-Sales Service).",
    49: "High temperature block on return probe. High temperature measured by the return probe → Make sure that water circulates properly in the boiler and that the three-way valve works properly.",
    50: "External probe anomaly. The external probe has an out of range resistive value → Check the external probe connection. The system keeps working",
    51: "CAR Wireless communication failure. Absent communication between base transmitter and CARv2 RF. → Check operation of the Wireless CAR, check the battery charge (refer to the relative instructions booklet).",
    54: "Puffer probe anomaly. The puffer probe has an out of range resistive value → The puffer mode is disabled",
    55: "Zone 1 flow temperature probe anomaly. The zone 1 flow probe has an out of range resistive value → If the block or anomaly persists, contact an authorised company (e.g. Immergas Technical After-Sales Service).",
    58: "Audax anomaly. Anomaly indication from the AUDAX heat pump connected to the system → The heat pump does not satisfy the room heating and cooling requests; once the connections are restored, switch the system on and off again",
    59: "Main supply voltage frequency block. The P.C.B. has detected an abnormal frequency on the power supply network. → The boiler does not start. If the shutdown or fault persists, contact an authorised company (e.g. Authorised Technical After-Sales Service).",
    60: "Anomaly pump blocked. The modulating pump is stopped. → Try to unblock the pump as described in the relative section. If normal conditions are restored the boiler restarts without having to be reset.",
    61: "Air in circulator pump. The modulating pump is stopped for air detected. → Vent the pump and the central heating circuit. If normal conditions are restored the boiler restarts without having to be reset.",
    62: "Complete calibration required. The P.C.B. not have the correct configuration of the combustion control parameters. → The boiler does not start. If the shutdown or fault persists, contact an authorised company (e.g. Authorised Technical After-Sales Service).",
    63: "System return probe anomaly. The return probe has an out of range resistive value → The boiler continues to operate without any integration from the external systems connected",
    67: "Solar system pressure switch anomaly. Open system pressure switch, possibly no fluid → Check on the pressure gauge of the solar circulation unit that the pressure is at the correct value",
    70: "Return/flow probe exchange → The boiler does not start. If the shutdown or fault persists, contact an authorised company (e.g. Authorised Technical After-Sales Service).",
    72: "Fast calibration required. The P.C.B. not have the correct configuration of some combustion control parameters. → The boiler does not start. If the shutdown or fault persists, contact an authorised company (e.g. Authorised Technical After-Sales Service).",
    73: "High flow probe and safety flow probe deviation detected. The delivery probes have a high variance. → If normal conditions are restored the boiler restarts without having to be reset.",
    74: "Safety flow probe anomaly. The safety flow sensor provides a resistive value out of range. → The boiler does not start. If the shutdown or fault persists, contact an authorised company (e.g. Authorised Technical After-Sales Service).",
    75: "Return and/or flow probe malfunction → The boiler does not start. If the shutdown or fault persists, contact an authorised company (e.g. Authorised Technical After-Sales Service).",
    76: "Return and/or flow probes temperature drift → The boiler does not start. If the shutdown or fault persists, contact an authorised company (e.g. Authorised Technical After-Sales Service).",
    77: "Combustion control anomaly. Gas valve current detected out of range. → The boiler does not start. If the shutdown or fault persists, contact an authorised company (e.g. Authorised Technical After-Sales Service).",
    78: "Combustion control anomaly. High current detected on gas valve. → The boiler does not start. If the shutdown or fault persists, contact an authorised company (e.g. Authorised Technical After-Sales Service).",
    79: "Combustion control anomaly. Low current detected on gas valve. → The boiler does not start. If the shutdown or fault persists, contact an authorised company (e.g. Authorised Technical After-Sales Service).",
    80: "P.C.B. malfunction block. Detected fault on gas valve electronic driver for problems on gas valve or P.C.B. → Press the Reset button",
    84: "Combustion anomaly - power reduction in progress. Detected conditions similar to low pressure feed gas valve. → If normal conditions are restored the boiler restarts without having to be reset",
    85: "Afterburner problem block. Potential gas valve, electrode or P.C.B. problem → Press the Reset button. If the shutdown or fault persists, contact an authorised company (e.g. Authorised Technical After-Sales Service).",
    87: "Block - gas valve control. Detected fault on gas valve control. → The boiler does not start. If the shutdown or fault persists, contact an authorised company (e.g. Authorised Technical After-Sales Service).",
    88: "Block - gas valve control. Detected fault on gas valve control. → The boiler does not start. If the shutdown or fault persists, contact an authorised company (e.g. Authorised Technical After-Sales Service).",
    89: "Combustion signal unstable. Detected instability of combustion signal. → The boiler keeps working.",
    90: "Combustion signal beyond limit. Detected combustion signal out of bounds. → The boiler keeps working.",
    91: "Incorrect ignition block. The P.C.B. has exhausted all of its possible actions for optimum ignition burner. → Press the Reset button",
    92: "Fan revs correction limit. The P.C.B. has reached the maximum fan speed correction. → The boiler keeps working.",
    93: "Combustion signal beyond limit. Detected combustion signal out of bounds. → The boiler keeps working.",
    94: "Combustion anomaly. Combustion problem detected caused by the system or control combustion. → If normal conditions are restored the boiler restarts without having to be reset.",
    95: "Combustion signal discontinuous. Detected discontinuities of combustion signal to problems of electrical connections or signal dispersion. → The boiler keeps working.",
    96: "Clogged flue. Detected high obstruction of the boiler assembly. → The boiler does not start. If the shutdown or fault persists, contact an authorised company (e.g. Authorised Technical After-Sales Service).",
    98: "Block - maximum no. of software errors. The P.C.B. is not working properly. → Press the Reset button",
    99: "General block. The P.C.B. is not working properly. → Press the Reset button",
    101: "Audax off-line alarm. Loss of communication with heat pump → The heat pump does not satisfy the room heating and cooling requests; once the connections are restored, switch the system on and off again",
    102: "Zone 1 off-line expansion alarm. Loss of communication with zone 1 expansion → If the block or anomaly persists, contact an authorised company (e.g. Immergas Technical After-Sales Service).",
    103: "Zone 2 off-line expansion alarm. Loss of communication with zone 2 expansion → If the block or anomaly persists, contact an authorised company (e.g. Immergas Technical After-Sales Service).",
    104: "Zone 3 off-line expansion alarm. Loss of communication with zone 3 expansion → If the block or anomaly persists, contact an authorised company (e.g. Immergas Technical After-Sales Service).",
    106: "DHW probe alarm. In the event of boiler integration and separate DHW management, the storage tank probe controlled by the operator has an out of range resistive value → The system cannot produce domestic hot water with the heat pump. The production of the domestic hot water is guaranteed by the boiler",
    120: "Zone 1 dehumidification high set alarm. The zone 1 request setpoint calculated is too high for dehumidification → The calculated flow set exceeds the limit permitted by the dehumidifier. Cool the room and wait until the dew temperature returns to acceptable values",
    121: "Zone 1 device offline alarm. The remote control or the remote control of zone 1 is offline → Check that the remote control is switched on",
    122: "Zone 2 device offline alarm. The remote control or the remote control of zone 2 is offline → Check that the remote control is switched on",
    123: "Zone 3 device offline alarm. The remote control or the remote control of zone 3 is offline → Check that the remote control is switched on",
    125: "Zone 1 room temperature probe anomaly. The room temperature probe of zone 1 is out of range → In addition to the temperature, the dew point is not calculated for the zone either",
    126: "Zone 2 room temperature probe anomaly. The room temperature probe of zone 2 is out of range → In addition to the temperature, the dew point is not calculated for the zone either",
    127: "Zone 3 room temperature probe anomaly. The room temperature probe of zone 3 is out of range → In addition to the temperature, the dew point is not calculated for the zone either",
    129: "Zone 1 humidity probe anomaly. The humidity probe of zone 1 is out of range → In addition to the humidity, the dew point is not calculated for the zone either",
    130: "Zone 2 humidity probe anomaly. The humidity probe of zone 2 is out of range → In addition to the humidity, the dew point is not calculated for the zone either",
    131: "Zone 3 humidity probe anomaly. The humidity probe of zone 3 is out of range → In addition to the humidity, the dew point is not calculated for the zone either",
    132: "Zone 2 dehumidification high set alarm. The zone 2 request setpoint calculated is too high for dehumidification → The calculated flow set exceeds the limit permitted by the dehumidifier. Cool the room and wait until the dew temperature returns to acceptable values",
    133: "Zone 1 dehumidifier fault alarm. The dehumidifier in zone 1 is in alarm conditions → The system does not dehumidify in the relative zone",
    134: "Zone 2 dehumidifier fault alarm. The dehumidifier in zone 2 is in alarm conditions → The system does not dehumidify in the relative zone",
    135: "Zone 3 dehumidifier fault alarm. The dehumidifier in zone 3 is in alarm conditions → The system does not dehumidify in the relative zone",
    137: "Reset system alarm – Restart the system. After a reset operation, which is performed via the control panel, an alarm is signalled because a system restart is required → Turn the system off and on",
    138: "Screed heater in progress. Screed heater function in progress",
    139: "Deaeration in progress. Deaeration function in progress",
    177: "DHW maximum time alarm. The DHW request was made exceeding a preset maximum time → The system continues to operate with non-optimal performance",
    178: "Anti-legionella cycle not successful. The anti-legionella cycle was not completed successfully within a preset time → Press the Reset button",
    179: "Liquid probe anomaly. The liquid phase probe is out of range. → The system does not start. Call an authorised company (e.g. Immergas Technical After-Sales Service).",
    181: "Remote Control communication failure zone 2. There is no dialogue between the board and the remote control in zone 2. → Disconnect and reconnect the power to the hydronic module. If the Remote Control is still not detected at restart, the system will switch to local operating mode, i.e. using the controls on the control panel. In this case the “Central Heating”, function cannot be activated",
    182: "Condensing unit alarm. An alarm is triggered on the condensing unit → The system does not work, see the anomaly on the condensing unit and its instructions booklet",
    183: "Condensing unit alarm in test mode. The condensing unit is in TEST MODE → During this time, room heating/air conditioning and domestic hot water production requirements cannot be met",
    184: "Communication with outdoor unit timeout alarm. Loss of communication with condensing unit → Have the electrical connection between the units checked",
    185: "Safety module communication alarm. Loss of communication with safety module → Have the electrical connection between the components checked",
    186: "Igniter high voltage anomaly. Safety module: there is an igniter voltage anomaly → If the block or anomaly persists, contact an authorised company (e.g. Immergas Technical After-Sales Service).",
    187: "Condensing unit return probe alarm. The condensing unit return probe is out of range → If the block or anomaly persists, contact an authorised company (e.g. Immergas Technical After-Sales Service).",
    188: "Request out of operating range. The request made is not performed because the outdoor conditions do not enable the activation of the condensing unit → If the block or anomaly persists, contact an authorised company (e.g. Immergas Technical After-Sales Service).",
    189: "Communication with communication board timeout alarm. Loss of communication with condensing unit communication board → If the block or anomaly persists, contact an authorised company (e.g. Immergas Technical After-Sales Service).",
    191: "RF communication failure towards CAR v2 RF zone 2. The communication between the transmitter base and the CAR v2 RF of zone 2 has failed → Check operation of the Wireless CAR, check the battery charge (refer to the relative instructions booklet)",
    192: "Condensing unit flow probe anomaly. The condensing unit flow probe is out of range → If the block or anomaly persists, contact an authorised company (e.g. Immergas Technical After-Sales Service).",
    193: "Appliance in Test mode. The appliance is controlled by an external device via the Opentherm protocol → The system continues operating properly",
    194: "Audax Pro disabled. The Audax Pro condensing unit has been disabled → The system continues operating properly",
    195: "Liquid phase low temp. anomaly. The temp. of the liquid phase probe is too low → Check that the cooling circuit is working properly",
    196: "High flow temp. block. An excessively high temperature is detected on the heat pump return circuit → Check that the cooling circuit is working properly",
}

DEFAULT_DESCRIPTION = "Anomaly not recognized. Check error table or system installed"

# Home Assistant caps a sensor state at 255 characters.
_MAX_STATE = 255


def describe(code: int) -> str:
    """Return an English description for a boiler fault code."""
    if code == 0:
        return "No faults"
    text = ANOMALIES.get(code, DEFAULT_DESCRIPTION)
    return f"E{code}: {text}"[:_MAX_STATE]
